// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWnlj8tW8EUV8zCv2t8f5QIEgxIfZpcWM',
    appId: '1:392189142551:web:0a09eda93a81233b741e52',
    messagingSenderId: '392189142551',
    projectId: 'lovetify-2ce34',
    authDomain: 'lovetify-2ce34.firebaseapp.com',
    storageBucket: 'lovetify-2ce34.firebasestorage.app',
    measurementId: 'G-HYGZ0NHBJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzp7wi2Otkpiiv_Ch1HAXJTj0QHhtQfI',
    appId: '1:392189142551:android:54d72bd1e37d1b3f741e52',
    messagingSenderId: '392189142551',
    projectId: 'lovetify-2ce34',
    storageBucket: 'lovetify-2ce34.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAigI_7xaE0c_-pkGncwP00oxozakshNYY',
    appId: '1:392189142551:ios:2d2c5539ee9c3eb3741e52',
    messagingSenderId: '392189142551',
    projectId: 'lovetify-2ce34',
    storageBucket: 'lovetify-2ce34.firebasestorage.app',
    iosBundleId: 'com.example.lovetify',
  );
}
